name: Test Password Strength

on:
  push:
    branches:
      -feat/password
    pull_request:
      branches:
        - main

jobs:
  test-password-strength:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run password strength test
        run: npm test -- src/password-calculator.ts test/password.test.ts

